// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CaseCountStats struct {
	New       int `json:"new"`
	Pending   int `json:"pending"`
	Completed int `json:"completed"`
}

type CaseSummary struct {
	ID              string   `json:"id"`
	CaseID          string   `json:"caseId"`
	Matter          string   `json:"matter"`
	ClientName      string   `json:"clientName"`
	Status          string   `json:"status"`
	NextHearing     *string  `json:"nextHearing,omitempty"`
	AssignedLawyers []string `json:"assignedLawyers"`
}

type Dashboard struct {
	Stats           *DashboardStats     `json:"stats"`
	CaseStatusChart []*StatusSlice      `json:"caseStatusChart"`
	MonthlyCases    []*MonthlyCasePoint `json:"monthlyCases"`
	RecentCases     []*CaseSummary      `json:"recentCases"`
}

type DashboardStats struct {
	Hearings *HearingStats   `json:"hearings"`
	Invoices *InvoiceStats   `json:"invoices"`
	Cases    *CaseCountStats `json:"cases"`
	Hr       *HRStats        `json:"hr"`
}

type HRStats struct {
	Total   int `json:"total"`
	Present int `json:"present"`
	Absent  int `json:"absent"`
}

type Health struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Env     string `json:"env"`
}

type HearingStats struct {
	Today     int `json:"today"`
	ThisMonth int `json:"thisMonth"`
	ThisYear  int `json:"thisYear"`
}

type InvoiceStats struct {
	Count         int     `json:"count"`
	Amount        float64 `json:"amount"`
	ReceiptCount  int     `json:"receiptCount"`
	ReceiptAmount float64 `json:"receiptAmount"`
}

type MonthlyCasePoint struct {
	Month string `json:"month"`
	Cases int    `json:"cases"`
}

// Law ERP GraphQL API — read-heavy dashboard and case queries.
type Query struct {
}

type StatusSlice struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
	Color string `json:"color"`
}
