package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/mr-aminul/law-erp/services/api/graph/generated"
	"github.com/mr-aminul/law-erp/services/api/graph/model"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	return r.Store.Health(r.Config.Env), nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*model.Dashboard, error) {
	first := 10
	return &model.Dashboard{
		Stats:           r.Store.DashboardStats(),
		CaseStatusChart: r.Store.CaseStatusChart(),
		MonthlyCases:    r.Store.MonthlyCases(),
		RecentCases:     r.Store.RecentCases(first),
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
